### ISSUE TITLE
implement the ws class

### ISSUE THREAD

**Issue by doodzik** [doodzik/bitcoin-websocket#2]
I've pushed what i have so far. The websocket class worked on its own in my environment.
Now it needs an implementation into the src:
- Access to the config in cWebsocket in order to authenticate the client
- Start the websocket Server if specified in the config
- Add the broadcast function where an event is triggered

**Comment by sandalsoft** [comment]
Perfect, thanks!  I'll get my environment up and start hacking on it this week.

**Comment by doodzik** [comment]
if you have any questions about the class just ask.

**Comment by doodzik** [comment]
i think zeromq would be better then websockets
